

---
- name: Install Specific versions of packages using Chocolatey
  hosts: windows
  gather_facts: false

  collections:
    - chocolatey.chocolatey 
  
  tasks: 

   - name: Remove the default public source
     win_chocolatey_source:
       name: chocolatey
       state: absent

   - name: Add new internal source
     chocolatey.chocolatey.win_chocolatey_source:
        name: internal repo
        state: present
        source: http://chocolatey-server/chocolatey

   - name: Gather facts from chocolatey
     win_chocolatey_facts:

   - name: Displays the configured chocolatey sources
     debug:
       var: ansible_chocolatey.sources