---
- name: Install packages using Chocolatey and Ansible Tower
  hosts: windows
  gather_facts: false


  tasks:

    - name: Install specific versions of packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
      loop: "{{ choco_packages }}"

  