---
- name: Update Chocolatey Features for Self-Service
  hosts: windows
  gather_facts: false

  collections:
    - chocolatey.chocolatey 
  
  vars: 
    choco_packages:
      - name: chocolatey-agent
      - name: chocolateygui

    

  tasks:

    - name: Install specific versions of packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        state: present
      loop: "{{ choco_packages }}"

    - name: Configure features for self-service
      chocolatey.chocolatey.win_chocolatey_feature:
        name: “{{ item }}”
        state: enabled
      loop:
        - useBackgroundService
        - useBackgroundServiceWithNonAdministratorsOnly
        - allowBackgroundServiceUninstallsFromUserInstallsOnly
