---
- name: Update Chocolatey Features for Self-Service
  hosts: windows
  gather_facts: false

  collections:
    - chocolatey.chocolatey 

  tasks:

    - name: Install chocolatey agent and gui
      chocolatey.chocolatey.win_chocolatey:
        name: “{{ item }}”
        state: latest
      loop:
        - chocolatey-agent
        - chocolateygui

    - name: Configure features for self-service
      chocolatey.chocolatey.win_chocolatey_feature:
        name: “{{ item }}”
        state: enabled
      loop:
        - useBackgroundService
        - useBackgroundServiceWithNonAdministratorsOnly
        - allowBackgroundServiceUninstallsFromUserInstallsOnly
