---
- name: Update Chocolatey Config
  hosts: windows
  gather_facts: false

  collections:
    - chocolatey.chocolatey 

  tasks:

   - name: Rate limit downloads
    chocolatey.chocolatey.win_chocolatey_config:
      name: maximumDownloadRateBitsPerSecond
      state: present
      value: 25000000