---
- name: Install Specific versions of packages using Chocolatey
  hosts: windows
  gather_facts: false

  collections:
    - chocolatey.chocolatey 
  
  tasks: 

   - name: Remove the default public source
     win_chocolatey_source:
       name: chocolatey
       state: present

   - name: Gather facts from chocolatey
     win_chocolatey_facts:

   - name: Displays the configured chocolatey sources
     debug:
       var: ansible_chocolatey.sources