---
- name: Install Specific versions of packages using Chocolatey
  hosts: windows
  gather_facts: false
  vars:
    choco_packages:
      - name: 7zip
        version: latest
    
  collections:
    - chocolatey.chocolatey 
  
  tasks:

    - name: Install latest version of packages.
      win_chocolatey:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      loop: "{{ choco_packages }}"

    