---
- name: Install Specific versions of packages using Chocolatey
  hosts: windows
  gather_facts: false
  vars:
    choco_packages:
      - name: nodejs
        version: 13.0.0
      - name: python
        version: 3.6.0
      - name: 7zip
        version: 19.0

  collections:
    - chocolatey.chocolatey 
 
  
  tasks:

    - name: Install specific versions of packages sequentially
      win_chocolatey:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      loop: "{{ choco_packages }}"

    - name: Check python version
      win_command: python --version
      register: check_python_version

    - name: Check nodejs version
      win_command: node --version
      register: check_node_version

    - debug:
        msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}